name: Deploy PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TinyTeX and LaTex deps
        run: |
          chmod +x ./scripts/install.ci.sh
          ./scripts/install.ci.sh

      - name: Install LaTeX (texlive)
        run: sudo apt-get update && sudo apt-get install -y texlive-full

      - name: Build PDF
        run: |
          pdflatex anteproyecto-jfmonsa.tex
          biber anteproyecto-jfmonsa
          pdflatex anteproyecto-jfmonsa.tex
          pdflatex anteproyecto-jfmonsa.tex

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thesis
          path: anteproyecto-jfmonsa.pdf

      # TODO: setup GitHub Pages to deploy the PDF
      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@3.6.2
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH: gh-pages
      #     CLEAN: true
      #     SINGLE_COMMIT: true
      #     FOLDER: out
      #     GIT_CONFIG_NAME: lukasbachbot
      #     GIT_CONFIG_EMAIL: bot@noreply.lukasbach.com
# Other Alternatives:
# - https://dev.to/mrturkmen/latex-with-github-actions-4580
# - https://tex.stackexchange.com/questions/664809/compile-latex-with-github-actions
# - https://github.com/marketplace/actions/latex-render-action-for-github
# - https://github.com/marketplace/actions/latex-action
# - https://github.com/DanySK/compile-latex-action
# - https://github.com/marketplace/actions/latex-compilation
# - https://github.com/marketplace/actions/github-action-for-latex
